import { FC, ReactNode } from "react";
import { Montserrat } from "next/font/google";
import type { Metadata } from "next";

import "./globals.scss";
import MainHeader from "@/components/layouts/header";

interface RootLayoutProps {
  children?: ReactNode;
}

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <MainHeader />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
